# Zotero Replication Checker Locale File
# Modern Fluent format (.ftl)

## Menu Items
replication-checker-tools-menu = Check Current Library for Replications
replication-checker-context-menu = Check for Replications
replication-checker-context-menu-ban = Ban Replication

## Progress Messages
replication-checker-progress-checking-library = Checking for Replications
replication-checker-progress-checking-collection = Checking for Replications in Collection
replication-checker-progress-scanning-library = Scanning library...
replication-checker-progress-scanning-collection = Scanning collection...
replication-checker-progress-found-dois = Found { $itemCount } items with DOIs ({ $uniqueCount } unique)
replication-checker-progress-checking-database = Checking against replication database...
replication-checker-progress-no-dois = No items with DOIs found in collection
replication-checker-progress-complete = Check Complete
replication-checker-progress-failed = Check Failed
replication-checker-progress-match-count = Found { $count } item(s) with replications
replication-checker-progress-copying-readonly = Copying items from read-only library to Personal library...

## Alerts
replication-checker-alert-title = Zotero Replication Checker
replication-checker-alert-no-dois-selected = No DOIs found in selected items.
replication-checker-alert-no-collection = Please select a collection before running this check.
replication-checker-error-title = Replication Checker - Error
replication-checker-error-api = Could not retrieve data from API - check your internet connection or retry again later.
replication-checker-error-body =
    Failed to check { $target } for replications:

    { $details }

    Could not retrieve data from API - check your internet connection or retry again later.
replication-checker-target-library = the current library
replication-checker-target-selected = the selected items
replication-checker-target-collection = the selected collection

## Ban Feature
replication-checker-ban-title = Ban Replications
replication-checker-ban-confirm =
    Are you sure you want to ban { $count } replication(s)?

    These items will be moved to trash and won't be re-added during future checks.
replication-checker-ban-success = Successfully banned { $count } replication(s).
replication-checker-alert-no-replications-selected = No replication items selected.

## Dialog
replication-checker-dialog-title = Replication Studies Found
replication-checker-dialog-intro = Replication studies found for:\n"{ $title }"
replication-checker-dialog-count = Found { $count } replication(s):
replication-checker-dialog-item = { $index }. { $title }\n({ $year })\n   Outcome: { $outcome }
replication-checker-dialog-more = ...and { $count } more replication(s)
replication-checker-dialog-question = Would you like to add replication information?
replication-checker-dialog-progress-title = Replication Information Added
replication-checker-dialog-progress-line = Added replication information to "{ $title }"

## Read-Only Library Handling
replication-checker-readonly-dialog-title = Read-Only Library Detected
replication-checker-readonly-dialog-message =
    This library is read-only. We found { $itemCount } item(s) with { $replicationCount } replication(s).

    Would you like to copy the original articles and their replications to your Personal library's "Replication folder"?

## Results Messages
replication-checker-results-title-library = Library Scan Complete
replication-checker-results-title-selected = Selected Items Scan Complete
replication-checker-results-title-collection = Collection Scan Complete
replication-checker-results-total = Total items checked: { $count }
replication-checker-results-dois = Items with DOIs: { $count }
replication-checker-results-found = { $count } item(s) have replications.
replication-checker-results-none = No replications found.
replication-checker-results-footer = View notes for details or select items to re-check.

## Tags
replication-checker-tag = Has Replication
replication-checker-tag-is-replication = Is Replication
replication-checker-tag-added-by-checker = Added by Replication Checker
replication-checker-tag-success = Replication: Successful
replication-checker-tag-failure = Replication: Failure
replication-checker-tag-mixed = Replication: Mixed
replication-checker-tag-readonly-origin = Original present in Read-Only Library

## Note Template
replication-checker-note-title = Replications Found
replication-checker-note-warning = This is an automatically generated note. Do not make changes!
replication-checker-note-intro = This study has been replicated:
replication-checker-note-feedback = Did you find this result useful? Provide feedback <a href="{ $url }" target="_blank">here</a>!
replication-checker-note-footer = Generated by Zotero Replication Checker using the FORRT Replication Database (FReD)

## Replication Item Details
replication-checker-li-no-title = No title available
replication-checker-li-no-authors = No authors available
replication-checker-li-no-journal = No journal
replication-checker-li-na = N/A
replication-checker-li-doi-label = DOI:
replication-checker-li-outcome = Author Reported Outcome:
replication-checker-li-link = This study has a linked report:

## First Run Prompt
replication-checker-prompt-title = Welcome to Zotero Replication Checker!
replication-checker-prompt-first-run =
    Thank you for installing the Zotero Replication Checker!

    This plugin helps you discover replication studies for your research by checking your library items against the FORRT Replication Database (FReD).

    Would you like to scan your library for replications now?

    • Click "Yes" to start scanning (this may take a few minutes)
    • Click "No" to skip - you can always scan later from Tools menu
