# Zotero Replication Checker Locale File
# Modern Fluent format (.ftl)

## Menu Items
replication-checker-tools-menu = Check Library for Replications
replication-checker-context-menu = Check for Replications

## Progress Messages
replication-checker-scanning = Scanning library...
replication-checker-found-dois = Found { $count } items with DOIs
replication-checker-checking-database = Checking against replication database...
replication-checker-processing = Processing results...

## Results Messages
replication-checker-complete = Scan complete
replication-checker-matches-found = { $count } replications found
replication-checker-no-matches = No replications found

## Alerts
replication-checker-no-selection = No items selected
replication-checker-no-dois = No DOIs found in selected items
replication-checker-error = Error checking for replications: { $message }

## Tags
replication-checker-tag = Has Replication

## Note Template
replication-checker-note-title = Replications Found
replication-checker-note-intro = This study has been replicated:
replication-checker-note-footer = Generated by Zotero Replication Checker using the FORRT Replication Database (FReD)
