// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'replication-checker-checking-database'
  | 'replication-checker-complete'
  | 'replication-checker-context-menu'
  | 'replication-checker-error'
  | 'replication-checker-found-dois'
  | 'replication-checker-matches-found'
  | 'replication-checker-no-dois'
  | 'replication-checker-no-matches'
  | 'replication-checker-no-selection'
  | 'replication-checker-note-footer'
  | 'replication-checker-note-intro'
  | 'replication-checker-note-title'
  | 'replication-checker-processing'
  | 'replication-checker-scanning'
  | 'replication-checker-tag'
  | 'replication-checker-tools-menu';
