// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "autoCheckFrequency": string;
      "autoCheckNewItems": boolean;
      "blacklist": string;
      "rootFolderName": string;
      "rootCollectionIDs": string;
      "collectionStructureVersion": number;
      "folderName": string;
      "reproductionFolderName": string;
      "collectionIDs": string;
      "reproductionCollectionIDs": string;
      "originalsReplicationFolderName": string;
      "originalsReplicationCollectionIDs": string;
      "originalsReproductionFolderName": string;
      "originalsReproductionCollectionIDs": string;
    };
  }
}
